---
title: "Alpha diversity heatmap comparisons"
author: "Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Alpha diversity heatmap comparisons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r load data, include = FALSE}

library("tmap")
library("leaflet")

# data(bird_heatmap_100m, bird_heatmap_20m, bird_heatmap_50m,
#      butt_heatmap_100m, butt_heatmap_20m, butt_heatmap_50m,
#      drag_heatmap_100m, drag_heatmap_20m, drag_heatmap_50m,
#      frog_heatmap_100m, frog_heatmap_20m, frog_heatmap_50m)

bird_heatmap_100m <- terra::rast("../data-raw/heatmaps/bird_heatmap_100m.tif")
bird_heatmap_50m <- terra::rast("../data-raw/heatmaps/bird_heatmap_50m.tif")
bird_heatmap_20m <- terra::rast("../data-raw/heatmaps/bird_heatmap_20m.tif")
butt_heatmap_100m <- terra::rast("../data-raw/heatmaps/butt_heatmap_100m.tif")
butt_heatmap_20m <- terra::rast("../data-raw/heatmaps/butt_heatmap_20m.tif")
butt_heatmap_50m <- terra::rast("../data-raw/heatmaps/butt_heatmap_50m.tif")
drag_heatmap_100m <- terra::rast("../data-raw/heatmaps/drag_heatmap_100m.tif")
drag_heatmap_50m <- terra::rast("../data-raw/heatmaps/drag_heatmap_50m.tif")
drag_heatmap_20m <- terra::rast("../data-raw/heatmaps/drag_heatmap_20m.tif")
frog_heatmap_100m <- terra::rast("../data-raw/heatmaps/frog_heatmap_100m.tif")
frog_heatmap_50m <- terra::rast("../data-raw/heatmaps/frog_heatmap_50m.tif")
frog_heatmap_20m <- terra::rast("../data-raw/heatmaps/frog_heatmap_20m.tif")
```

```{r plotting maps, include = FALSE}
# Plotting maps

tmap_mode("view")
# tmap_mode("plot")
tmap_options(check.and.fix = TRUE, #turf, natveg and shrubs layers contain invalid polygons
             max.raster = c(plot = 1e7, view = 1e8)) # increase max raster resolution 

tm <- 
  tm_basemap(c("CartoDB.Positron", "CartoDB.DarkMatter", "OpenStreetMap")) +

  #100m heatmaps
  tm_shape(bird_heatmap_100m, raster.downsample = FALSE) +
    tm_raster(title = "Bird SR",
                group = paste0("Bird Heatmap Raster ", 100, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(butt_heatmap_100m, raster.downsample = FALSE) +
    tm_raster(title = "Butt SR",
                group = paste0("Butterfly Heatmap Raster ", 100, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(drag_heatmap_100m, raster.downsample = FALSE) +
    tm_raster(title = "Odonate SR",
                group = paste0("Odonate Heatmap Raster ", 100, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(frog_heatmap_100m, raster.downsample = FALSE) +
    tm_raster(title = "Amphibian SR",
                group = paste0("Amphibian Heatmap Raster ", 100, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  #50m heatmaps
  tm_shape(bird_heatmap_50m, raster.downsample = FALSE) +
    tm_raster(title = "Bird SR",
                group = paste0("Bird Heatmap Raster ", 50, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(butt_heatmap_50m, raster.downsample = FALSE) +
    tm_raster(title = "Butt SR",
                group = paste0("Butterfly Heatmap Raster ", 50, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(drag_heatmap_50m, raster.downsample = FALSE) +
    tm_raster(title = "Odonate SR",
                group = paste0("Odonate Heatmap Raster ", 50, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(frog_heatmap_50m, raster.downsample = FALSE) +
    tm_raster(title = "Amphibian SR",
                group = paste0("Amphibian Heatmap Raster ", 50, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  #20m heatmaps
  tm_shape(bird_heatmap_20m, raster.downsample = FALSE) +
    tm_raster(title = "Bird SR",
                group = paste0("Bird Heatmap Raster ", 20, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(butt_heatmap_20m, raster.downsample = FALSE) +
    tm_raster(title = "Butt SR",
                group = paste0("Butterfly Heatmap Raster ", 20, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(drag_heatmap_20m, raster.downsample = FALSE) +
    tm_raster(title = "Odonate SR",
                group = paste0("Odonate Heatmap Raster ", 20, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) +
  
  tm_shape(frog_heatmap_20m, raster.downsample = FALSE) +
    tm_raster(title = "Amphibian SR",
                group = paste0("Amphibian Heatmap Raster ", 20, "m"),
                style = "pretty",
                palette = "YlOrRd",
                # labels = c(" "),
              #legend.show = FALSE,
                alpha = 0.8) 
  
```

```{r leaflet, echo = FALSE, warning = FALSE, message = FALSE, fig.width=2.6, fig.height = 2.0, dpi = 300, cache = TRUE}
# Pipe the tmap object into tmap_leaflet() to create a leaflet widget,
# so that we can use leaflet::hideGroup().
tm %>% 
  tmap_leaflet() %>%
  
  leaflet::hideGroup("Butterfly Heatmap Raster 100m") %>%
  leaflet::hideGroup("Butterfly Heatmap Raster 50m") %>% 
  leaflet::hideGroup("Butterfly Heatmap Raster 20m") %>% 
  leaflet::hideGroup("Odonate Heatmap Raster 100m") %>% 
  leaflet::hideGroup("Odonate Heatmap Raster 50m") %>% 
  leaflet::hideGroup("Odonate Heatmap Raster 20m") %>% 
  leaflet::hideGroup("Amphibian Heatmap Raster 100m") %>% 
  leaflet::hideGroup("Amphibian Heatmap Raster 50m") %>% 
  leaflet::hideGroup("Amphibian Heatmap Raster 20m")
  
  
```

```{r rm obj, include = FALSE}
rm(bird_heatmap_100m, bird_heatmap_20m, bird_heatmap_50m,
   butt_heatmap_100m, butt_heatmap_20m, butt_heatmap_50m,
   drag_heatmap_100m, drag_heatmap_20m, drag_heatmap_50m,
   frog_heatmap_100m, frog_heatmap_20m, frog_heatmap_50m)
```

