---
title: "Otsu's thresholding"
author: "Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Otsu's thresholding}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

To make sense of the raster data, the important information (e.g. landscape metrics) has to be isolated from the noise. Otsu's thresholding ([Otsu, 1979](https://cw.fel.cvut.cz/wiki/_media/courses/a6m33bio/otsu.pdf)) is an automated threshold finder that outperforms other techniques in terms of stability of results and processing speed, even with the presence of >2 peaks in the histogram ([Bouhennache et al., 2019](https://www.tandfonline.com/doi/abs/10.1080/10106049.2018.1497094)). The NDVI threshold for vegetation typically ranges from 0.2 to 0.4 ([Wong et al, 2019](https://link.springer.com/article/10.1186/s40562-019-0132-4); [Akbar et al, 2019](https://www.mdpi.com/2072-4292/11/2/105)). Setting a threshold value for each index allows for the assignment of pixels with the absence or presence of the respective land cover type, which facilitates the classification of raster files. 

```{r otsu thresholding, eval = FALSE}
veg_classified <- data(mosaic)

# get threshold value via otsu method (assumes bimodal histogram)
threshold <- list()
for(i in 1:length(rounds)){
  thresholds[[i]] <- threshold_otsu(veg_classified[i], levels = 256) #default levels = 256 for 8-bit images
  rm(i)
}

# view thresholds
thresholds[[1]]
#[value 1]
```

![**Distribution of NDVI values across Singapore in Survey Round One (light green bars, dashed vertical lines) and Two (dark green bars, solid vertical lines).** Based on image mosaic composed of data captured for Survey Round One and Survey Round Two. Vegetation was classified as pixel with values >0.35 for Round One and >0.36 for Round Two, via Otsu's thresholding. Dense vegetation was classified as pixels with values >0.62 for Round One and >0.64 for Round Two, using the same method after the first round of classification.](otsu-sample-plot.png){#id .class width=60% height=60%}
